### ISSUE TITLE
내 선수단 관리 리스트 반영

### ISSUE THREAD

**Issue by dart-bird** [krumaska/ERICA_LOL#2]
내선수관리 리스트 반영시 
```
>>>>선발<<<<
testuser,dx790112!,0,10000,T1,0,nullnullnullnullnull
>>>>후보<<<<
Exception in thread "main" java.lang.NumberFormatException: For input string: "22
"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at ClassSet.Content.UserContent.getUserDeck(UserContent.java:135)
        at ClassSet.MFrame.Mframe.showMyplayerList(Mframe.java:28)
        at ClassSet.MFrame.Mframe.mypage(Mframe.java:46)
        at Main.main(Main.java:21)
```
라는 오류와 함께 쓰레기 값도 들어감

**Comment by dart-bird** [comment]
22 뒤에 \n 이 들어가서 문자열을 정수로 변환 할때 오류가 발생했었음.
playerdata.gdata 경로를 추가로 주지않아서 사용자 정보값이 들어간거였음.
